const INVALID_DATA_ERROR_CODE = 400;
const SERVER_ERROR_CODE = 500;
const DATA_NOT_FOUND_ERROR_CODE = 404;
const UNAUTHORIZED_DATA_CODE = 403;

module.exports = {INVALID_DATA_ERROR_CODE, SERVER_ERROR_CODE, DATA_NOT_FOUND_ERROR_CODE,UNAUTHORIZED_DATA_CODE};